
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vBoxMain;

	private global::Gtk.HBox hBoxTop;

	private global::Gtk.HBox hBoxBottom;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBoxMain = new global::Gtk.VBox();
		this.vBoxMain.Name = "vBoxMain";
		this.vBoxMain.Spacing = 6;
		// Container child vBoxMain.Gtk.Box+BoxChild
		this.hBoxTop = new global::Gtk.HBox();
		this.hBoxTop.Name = "hBoxTop";
		this.hBoxTop.Spacing = 6;
		this.vBoxMain.Add(this.hBoxTop);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vBoxMain[this.hBoxTop]));
		w1.Position = 0;
		// Container child vBoxMain.Gtk.Box+BoxChild
		this.hBoxBottom = new global::Gtk.HBox();
		this.hBoxBottom.Name = "hBoxBottom";
		this.hBoxBottom.Spacing = 6;
		this.vBoxMain.Add(this.hBoxBottom);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBoxMain[this.hBoxBottom]));
		w2.Position = 1;
		this.Add(this.vBoxMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
